// The Worker itself.
//
// Everything a request does is already handled by the worker the Next.js
// adapter generates — this wraps it only to add the one thing Cloudflare
// cannot deliver through a request: the schedule.
//
// Cloudflare does not call a URL on a timer the way Vercel does. It calls a
// `scheduled` function on the Worker, and the generated worker has no such
// function, so without this file the nightly Google Sheet copy and the morning
// diamond-receipt check would simply never run. Both routes stay ordinary URLs
// a person can also open; this only presses them.
//
// The generated worker does not exist until `opennextjs-cloudflare build` has
// run, which is why the imports below are written the way they are. The three
// re-exported classes are the adapter's own — dropping them silently breaks
// caching, so they are passed straight through.

// ts-ignore rather than ts-expect-error: the file it points at is generated by
// the build, so whether TypeScript can resolve it depends on whether anyone has
// run the build yet. ts-expect-error would then be the failure — unused —
// on exactly the machines where everything is fine.
//
// @ts-ignore — generated by the build, resolved by wrangler.
import openNext from "../.open-next/worker.js";
// @ts-ignore — generated by the build, resolved by wrangler.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "../.open-next/worker.js";

type Env = {
  CRON_SECRET?: string;
  [key: string]: unknown;
};

// Scheduled runs never leave the Worker — this request is handed straight to
// the handler as a function call — and neither scheduled route reads the host.
// So the origin is a constant rather than the portal's real address, which
// saves keeping a domain name in step with reality in a third place.
const INTERNAL_ORIGIN = "https://seyaa-order.internal";

// Which schedule presses which button. The keys are the cron expressions from
// wrangler.jsonc exactly as written — Cloudflare hands back the string it was
// given, so the two have to agree character for character.
const SCHEDULE: Record<string, { path: string; what: string }> = {
  "30 18 * * *": { path: "/api/backup/sheets", what: "nightly Google Sheet copy" },
  "35 2 * * 1-6": { path: "/api/receipt-chase/tick", what: "diamond receipt check" },
};

export default {
  fetch: openNext.fetch,

  // Run a scheduled job by asking the app for the route, so the schedule goes
  // through exactly the code a person pressing the button does — same
  // middleware, same authentication, same handler. There is no second way in.
  async scheduled(event: ScheduledController, env: Env, ctx: ExecutionContext): Promise<void> {
    const job = SCHEDULE[event.cron];
    if (!job) {
      console.error(`No job is mapped to the schedule "${event.cron}" — nothing ran.`);
      return;
    }

    // Both routes accept the scheduler's bearer token, the same one Vercel's
    // cron used. Without it the middleware answers 401 and the job does
    // nothing, quietly — which is how the Google Sheet copy went stale for a
    // fortnight once before.
    const secret = env.CRON_SECRET;
    if (!secret) {
      console.error(`CRON_SECRET is not set, so the ${job.what} cannot authenticate.`);
      return;
    }

    const request = new Request(`${INTERNAL_ORIGIN}${job.path}`, {
      headers: { authorization: `Bearer ${secret}` },
    });

    const response: Response = await openNext.fetch(request, env, ctx);
    if (!response.ok) {
      console.error(`The ${job.what} answered ${response.status}: ${await response.text()}`);
    }
  },
};
